//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace УспеваемостьСтудентов
{
    using System;
    using System.Collections.Generic;
    
    public partial class Успеваемость
    {
        public int ID_Успеваемости { get; set; }
        public Nullable<int> id_предмета { get; set; }
        public Nullable<int> Рейтинг_КН { get; set; }
        public Nullable<System.DateTime> Дата_сдачи { get; set; }
        public string Оценка { get; set; }
        public Nullable<int> id_студента { get; set; }
        public Nullable<int> id_преподавателя { get; set; }
    
        public virtual Предметы Предметы { get; set; }
        public virtual Преподаватели Преподаватели { get; set; }
        public virtual Студенты Студенты { get; set; }
    }
}
